export const FETCH_INCIDENTS_SUCCESS = 'FETCH_INCIDENTS_SUCCESS';
export const ADD_NOTE = 'ADD_NOTE';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const INCIDENTS_LOADING = 'INCIDENTS_LOADING';
