export const LOAD_INCIDENTS_SUCCESS = 'LOAD_INCIDENTS_SUCCESS';
export type LOAD_INCIDENTS_SUCCESS = typeof LOAD_INCIDENTS_SUCCESS;

export const INITIATE_AJAX_CALL = 'INITIATE_AJAX_CALL';
export type INITIATE_AJAX_CALL = typeof INITIATE_AJAX_CALL;
