export const CREATE_INCIDENT_SUCCESS = 'CREATE_INCIDENT_SUCCESS';
export type CREATE_INCIDENT_SUCCESS = typeof CREATE_INCIDENT_SUCCESS;

export const LOAD_INCIDENTS_SUCCESS = 'LOAD_INCIDENTS_SUCCESS';
export type LOAD_INCIDENTS_SUCCESS = typeof LOAD_INCIDENTS_SUCCESS;

export const INITIATE_AJAX_CALL = 'INITIATE_AJAX_CALL';
export type INITIATE_AJAX_CALL = typeof INITIATE_AJAX_CALL;

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export type LOAD_CATEGORIES_SUCCESS = typeof LOAD_CATEGORIES_SUCCESS;
